compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
mixed_precision: bf16
downcast_bf16: 'no'
num_processes: 8
main_training_function: main
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false