# Training parameters
dry: false
num_epochs: 100
warmup_steps: 4000
enable_compilation: false
skip_training: false
log_to_wandb: false

# Optimizer settings
optimizer_type: "adamw"
learning_rate: 5.0e-4
min_learning_rate: 5.0e-5
optimizer_betas: [0.9, 0.95]
optimizer_epsilon: 1.0e-8
optimizer_weight_decay: 1.0e-1
optimizer_fused: true

# Model architecture
img_size: [180, 360]  # matches data dimensions
patch_size: 4  # results in 45x90 patches
embed_dim: 2048  # large embedding dimension
depth: 20  # many transformer layers
decoder_depth: 8  # many decoder layers
num_heads: 16  # more attention heads
mlp_ratio: 4.0  # standard MLP ratio
drop_path: 0.2  # increased regularization
drop_rate: 0.1

# Lead time settings
lead_time_set: [6]  # prediction horizons in hours

# Data loading
batch_size: 1
num_workers: 8
shuffle: true
pin_memory: true
prefetch_factor: 2
persistent_workers: true
multiprocessing_context: "spawn"

# Data configuration
stats_path: "/mnt/data/jua-silver-layer/all_variables_stats_together.json"
zarr_path: "/mnt/data/jua-bronze-layer/scratch/alex/erax5-toy-2004-2023-180x360.zarr"
start_date: "1979-01-01"
end_date: "2019-12-31"
levels: [100, 500, 1000]  # pressure levels in hPa

# Variables configuration
input_variable_names:
  - "air_temperature_2m"
  - "air_pressure_at_mean_sea_level"
  - "air_temperature"
  - "geopotential"
  - "eastward_wind"
  - "northward_wind"
  - "surface_pressure"
  - "relative_humidity"
output_variable_names:
  - "air_temperature_2m"
  - "air_pressure_at_mean_sea_level"
  - "air_temperature"
  - "geopotential"
  - "eastward_wind"
  - "northward_wind"
  - "surface_pressure"
  - "relative_humidity" 